# Generated by Django 3.2.10 on 2021-12-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Published',
            new_name='published',
        ),
    ]
