# Generated by Django 3.2.10 on 2022-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default=0, upload_to='book_pdf/'),
            preserve_default=False,
        ),
    ]
