# Generated by Django 3.2.10 on 2022-06-06 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(upload_to='book_pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
